### ISSUE TITLE
战网API地址拼接有误

### ISSUE THREAD

**Issue by jcreator35** [AeanSR/irecore#1]
项目中的battlenet.cpp文件里的战网api地址字符串拼接有误，连接国服是正常，但是连接台服(或者欧服及其他服)就错了。
例如台服的api地址应是”https://tw.api.net/wow/xxxxx“，而你却拼接成”https://twapi.net/wow/xxxxx“，少了一个点

**Comment by AeanSR** [comment]
Fixed in https://github.com/AeanSR/irecore/commit/cb94b3c2b7418cd5dd0bf33e6cbdd01f7dd5fc77.
