### ISSUE TITLE
属性的值计算有误

### ISSUE THREAD

**Issue by jcreator35** [AeanSR/irecore#2]
导入战网数据后，发现有2个问题：
一.+75暴击的紫色宝石程序里一律都只计算成+74暴击(其他属性的紫色宝石没试，不知是否还会有这个bug)，
二.饰品上若有插槽插了+75暴击的紫色宝石，程序却未把这部分的暴击数值加上

**Comment by AeanSR** [comment]
1. Fixed in 00ddf44.
2. 未能再现，能否提供出现问题的角色英雄榜？疑似战网本身的BUG。

**Comment by jcreator35** [comment]
今天获取了新代码，发现ok了，饰品那部分没问题，是我计算错了。
